//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOSS.UIAndFeatureManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MOSS.UIAndFeatureManager.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _150px_Question_Mark_Icon___Blue_Box_svg {
            get {
                object obj = ResourceManager.GetObject("_150px_Question_Mark_Icon___Blue_Box_svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string customWebParts {
            get {
                return ResourceManager.GetString("customWebParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_about {
            get {
                object obj = ResourceManager.GetObject("icon_about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_close {
            get {
                object obj = ResourceManager.GetObject("icon_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_copy {
            get {
                object obj = ResourceManager.GetObject("icon_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_cut {
            get {
                object obj = ResourceManager.GetObject("icon_cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_open {
            get {
                object obj = ResourceManager.GetObject("icon_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_paste {
            get {
                object obj = ResourceManager.GetObject("icon_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_save {
            get {
                object obj = ResourceManager.GetObject("icon_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_saveas {
            get {
                object obj = ResourceManager.GetObject("icon_saveas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NextDocs_AboutPage
        ///NextDocs_AdminLinks
        ///NextDocs_AdvancedSearch
        ///NextDocs_ChangeRequest
        ///NextDocs_Columns_MVT
        ///NextDocs_ContentTypes_MVT
        ///NextDocs_ContentTypes_SOP
        ///NextDocs_ConvertToPDF
        ///NextDocs_CoSign
        ///NextDocs_DatabaseAdmin
        ///NextDocs_DocLib_CB
        ///NextDocs_DocLib_DM
        ///NextDocs_DocLib_MVT_Reports
        ///NextDocs_DocumentAuditWP
        ///NextDocs_LifecycleWP
        ///NextDocs_MetadataTagging
        ///NextDocs_PasswordChange
        ///NextDocs_PdfCollab
        ///NextDocs_Publish
        ///NextDocs_PublishToPDF
        ///NextDocs_QM_Lists_Apparatus
        ///NextDocs_QM_Lists_Appara [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nextDocsFeatures {
            get {
                return ResourceManager.GetString("nextDocsFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NintexWorkflow
        ///NintexWorkflowAdmin
        ///NintexWorkflowContentTypeUpgrade
        ///NintexWorkflowWeb
        ///NintexWorkflowWebParts.
        /// </summary>
        internal static string nintexFeatures {
            get {
                return ResourceManager.GetString("nintexFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddDashboard, 
        ///AdminLinks,  
        ///Analytics, 
        ///AnalyticsLinks, 
        ///AnnouncementsList, 
        ///BaseSite, 
        ///BaseSiteStapling, 
        ///BaseWeb, 
        ///BaseWebApplication, 
        ///BasicWebParts, 
        ///BDCAdminUILinks, 
        ///BDR, 
        ///BizAppsCTypes, 
        ///BizAppsFields, 
        ///BizAppsListTemplates, 
        ///BizAppsSiteTemplates, 
        ///BulkWorkflow, 
        ///BulkWorkflowTimerJob, 
        ///ContactsList, 
        ///ContentLightup, 
        ///ContentTypeSettings, 
        ///CTypes, 
        ///CustomList, 
        ///DataConnectionLibrary, 
        ///DataConnectionLibraryStapling, 
        ///DataSourceLibrary, 
        ///DeploymentLinks, 
        ///DiscussionsList, 
        ///D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sharePoint2007Features {
            get {
                return ResourceManager.GetString("sharePoint2007Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Office.Server.Search.WebControls
        ///Microsoft.SharePoint.Portal.WebControls
        ///Microsoft.SharePoint.WebPartPages.
        /// </summary>
        internal static string sharePoint2007WebParts {
            get {
                return ResourceManager.GetString("sharePoint2007WebParts", resourceCulture);
            }
        }
    }
}
